[tool.poetry]
name = "hypermodern-python-website"
version = "0.1.0"
description = ""
authors = ["Claudio Jolowicz <mail@claudiojolowicz.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
Sphinx = "^3.3.1"
sphinx-autobuild = "^2020.9.1"
myst-parser = "^0.12.10"
furo = "^2020.11.14-beta.16"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
